[project]
name = "Eager_Beaver_bot"
version = "0.1.0"
description = "This bot was created thanks to a very kind person"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytelegrambotapi>=4.27.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.0",
]